spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: ${ENV_MYSQL_ROOT_USERNAME:root}
    password: ${ENV_MYSQL_ROOT_PASSWORD:Mysql@123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/