spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: ${ENV_MYSQL_ROOT_USERNAME:root}
    password: ${ENV_MYSQL_ROOT_PASSWORD:Mysql@123}

server:
  port: 8082
